// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tulip.proto

package com.github.iapt_platform.mint.plugins.tulip.v1;

public interface SearchRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mint.tulip.v1.SearchRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string keywords = 1;</code>
   * @return A list containing the keywords.
   */
  java.util.List<java.lang.String>
      getKeywordsList();
  /**
   * <code>repeated string keywords = 1;</code>
   * @return The count of keywords.
   */
  int getKeywordsCount();
  /**
   * <code>repeated string keywords = 1;</code>
   * @param index The index of the element to return.
   * @return The keywords at the given index.
   */
  java.lang.String getKeywords(int index);
  /**
   * <code>repeated string keywords = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the keywords at the given index.
   */
  com.google.protobuf.ByteString
      getKeywordsBytes(int index);

  /**
   * <code>int32 book = 2;</code>
   * @return The book.
   */
  int getBook();

  /**
   * <code>optional .mint.tulip.v1.SearchRequest.Page page = 99;</code>
   * @return Whether the page field is set.
   */
  boolean hasPage();
  /**
   * <code>optional .mint.tulip.v1.SearchRequest.Page page = 99;</code>
   * @return The page.
   */
  com.github.iapt_platform.mint.plugins.tulip.v1.SearchRequest.Page getPage();
  /**
   * <code>optional .mint.tulip.v1.SearchRequest.Page page = 99;</code>
   */
  com.github.iapt_platform.mint.plugins.tulip.v1.SearchRequest.PageOrBuilder getPageOrBuilder();
}
