// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: morus.proto

package com.github.iapt_platform.mint.plugins.morus.v1;

public interface MarkdownToHtmlResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mint.morus.v1.MarkdownToHtmlResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string payload = 1;</code>
   * @return The payload.
   */
  java.lang.String getPayload();
  /**
   * <code>string payload = 1;</code>
   * @return The bytes for payload.
   */
  com.google.protobuf.ByteString
      getPayloadBytes();
}
