- name: Create clove folder
  become: true
  ansible.builtin.file:
    path: "{{ app_deploy_target | dirname }}/clove"
    state: directory
    owner: "{{ ansible_user }}"
    mode: "0755"

- name: Upload clove data
  ansible.builtin.unarchive:
    src: "{{ playbook_dir }}/tmp/clove.tar.xz"
    dest: "{{ app_deploy_target | dirname }}/clove"
    creates: "{{ app_deploy_target | dirname }}/clove/dict_text"

- name: Setup clove resources for v8
  ansible.builtin.file:
    src: "{{ app_deploy_target | dirname }}/clove"
    dest: "{{ app_deploy_target }}/api-v8/storage/resources"
    state: link
    force: true

- name: Setup clove resources for v12
  ansible.builtin.file:
    src: "{{ app_deploy_target | dirname }}/clove"
    dest: "{{ app_deploy_target }}/api-v12/storage/resources"
    state: link
    force: true
