- name: Upload .env(v2)
  ansible.builtin.template:
    src: v2/env.j2
    dest: "{{ app_deploy_target }}/api-v8/.env"
    mode: "0444"

- name: Upload config.php(v1)
  ansible.builtin.template:
    src: v1/config.php.j2
    dest: "{{ app_deploy_target }}/api-v8/public/app/config.php"
    mode: "0444"

- name: Upload config.js(v1)
  ansible.builtin.template:
    src: v1/config.js.j2
    dest: "{{ app_deploy_target }}/api-v8/public/app/config.js"
    mode: "0444"

- name: "Setup configuration"
  ansible.builtin.shell:
    cmd: "docker run --rm -it --hostname=mint --network host -v /srv/{{ app_domain }}/clove:/srv/{{ app_domain }}/clove:z -v {{ app_deploy_target }}/api-v8:{{ app_deploy_target }}/api-v8:z {{ app_docker_image_name }} {{ app_deploy_target }}/scripts/run.sh setup"

- name: Create a current link
  ansible.builtin.file:
    src: "{{ app_deploy_target }}"
    dest: "{{ app_deploy_target | dirname }}/current"
    state: link
