[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "rhododendron"
version = "2026.6.28"
authors = [
    { name = "Visuddhinanda", email = "visuddhinanda@gmail.com" },
    { name = "Kassapa", email = "ven.kassapa@qq.com" },
]
description = "A LLM service"
readme = "README.md"
requires-python = ">=3.14"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
dependencies = ["bottle", "langchain"]

[project.urls]
Homepage = "https://github.com/iapt-platform/mint/tree/master/langchain-server"
Issues = "https://github.com/iapt-platform/mint/issues"

[project.scripts]
rhododendron = "rhododendron.__main__:main"
