- name: Create scripts folder
  ansible.builtin.file:
    path: "{{ app_deploy_target }}/scripts"
    state: directory
    mode: "0755"

- name: Upload laravel.sh
  ansible.builtin.template:
    src: laravel.sh.j2
    dest: "{{ app_deploy_target }}/scripts/laravel.sh"
    mode: "0555"

- name: Setup api-v8
  ansible.builtin.command: docker run --rm -it -v /srv:/srv:z {{ app_php81_image }} {{ app_deploy_target }}/scripts/laravel.sh setup
  
- name: Setup api-v12
  ansible.builtin.command: docker run --rm -it -v /srv:/srv:z {{ app_php84_image }} {{ app_deploy_target }}/scripts/laravel.sh setup
  