- name: Upload laravel-scheduler.service({{ item.version }})
  become: true
  ansible.builtin.template:
    src: laravel-scheduler.service.j2
    dest: "/etc/systemd/system/{{ app_domain }}-laravel-scheduler-{{ item.version }}.service"
    mode: "0444"

- name: Upload laravel-scheduler.timer({{ item.version }})
  become: true
  ansible.builtin.template:
    src: laravel-scheduler.timer.j2
    dest: "/etc/systemd/system/{{ app_domain }}-laravel-scheduler-{{ item.version }}.timer"
    mode: "0444"
