- name: Pull docker image
  ansible.builtin.command: docker pull {{ item }}
  with_items:
    - "{{ app_php81_image }}"
    - "{{ app_php84_image }}"
    - "{{ app_python_image }}"
    - "{{ app_nodejs_image }}"
  when: app_pull_images

- name: Create /srv/python3 folder
  become: true
  ansible.builtin.file:
    path: /srv/python3
    state: directory
    owner: "{{ ansible_user }}"
    mode: "0755"

- name: Extract python3.tar.xz
  ansible.builtin.unarchive:
    src: python3-{{ ansible_facts['architecture'] }}-2026011614.tar.xz
    dest: /srv
    creates: /srv/python3/pyvenv.cfg

- name: Create workspace folder
  become: true
  ansible.builtin.file:
    path: "{{ app_deploy_target | dirname }}"
    state: directory
    owner: "{{ ansible_user }}"
    mode: "0755"

- name: Create scripts folder
  ansible.builtin.file:
    path: "{{ app_deploy_target }}"
    state: directory
    mode: "0755"

- name: Extract release
  ansible.builtin.unarchive:
    src: "{{ playbook_dir }}/tmp/{{ app_domain }}-{{ mint_version }}.tar.xz"
    dest: "{{ app_deploy_target }}"
    creates: "{{ app_deploy_target }}/api-v12"

- name: Upload configurations
  ansible.builtin.import_tasks: config.yml

- name: Setup laravel
  ansible.builtin.import_tasks: laravel-setup.yml

- name: Setup systemd services
  ansible.builtin.import_tasks: systemd.yml
