- name: Pull {{ item }} image
  ansible.builtin.shell: docker pull {{ item }}
  with_items:
    - "{{ app_php81_image }}"
    - "{{ app_php84_image }}"
    - "{{ app_python_image }}"
    - "{{ app_nodejs_image }}"

- name: Create workspace folder
  become: true
  ansible.builtin.file:
    path: "{{ app_deploy_target | dirname }}"
    state: directory
    owner: "{{ ansible_user }}"
    mode: "0755"

- name: Create scripts folder
  ansible.builtin.file:
    path: "{{ app_deploy_target }}"
    state: directory
    mode: "0755"

- name: Extract release
  ansible.builtin.unarchive:
    src: "{{ playbook_dir }}/tmp/{{ app_domain }}-{{ mint_version }}.tar.xz"
    dest: "{{ app_deploy_target }}"
    creates: "{{ app_deploy_target }}/api-v12"

- name: Upload configurations
  ansible.builtin.import_tasks: config.yml

- name: Setup systemd services
  ansible.builtin.import_tasks: systemd.yml
