# - name: Upload assets folder
#   become: true
#   ansible.builtin.copy:
#     src: public
#     dest: /var/www/{{ inventory_hostname }}
#     owner: www-data
#     group: www-data

- name: Upload assets folder
  ansible.posix.synchronize:
    src: public
    dest: /var/www/{{ inventory_hostname }}

- name: upload nginx.conf
  become: true
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: "/etc/nginx/sites-enabled/{{ inventory_hostname }}.conf"
    owner: www-data
    group: www-data
    mode: '0400'
