# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: lily.proto for package 'palm.lily.v1'

require 'grpc'
require 'lily_pb'

module Palm
  module Lily
    module V1
      module Excel
        # ----------------------------------------------------------------------------
        #
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'palm.lily.v1.Excel'

          rpc :Parse, ::Palm::Lily::V1::File, ::Palm::Lily::V1::ExcelModel
          rpc :Generate, ::Palm::Lily::V1::ExcelModel, ::Palm::Lily::V1::File
        end

        Stub = Service.rpc_stub_class
      end
      module Tex
        # ----------------------------------------------------------------------------
        #
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'palm.lily.v1.Tex'

          rpc :ToPdf, ::Palm::Lily::V1::TexToRequest, ::Palm::Lily::V1::File
          rpc :ToWord, ::Palm::Lily::V1::TexToRequest, ::Palm::Lily::V1::File
        end

        Stub = Service.rpc_stub_class
      end
      module Epub
        # ----------------------------------------------------------------------------
        #
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'palm.lily.v1.Epub'

          rpc :Build, ::Palm::Lily::V1::EpubBuildRequest, ::Palm::Lily::V1::File
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
