<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lily.proto

namespace Palm\Lily\V1\TeXLiveTask\Output;

use UnexpectedValueException;

/**
 * Protobuf type <code>palm.lily.v1.TeXLiveTask.Output.Format</code>
 */
class Format
{
    /**
     * Generated from protobuf enum <code>Pdf = 0;</code>
     */
    const Pdf = 0;

    private static $valueToName = [
        self::Pdf => 'Pdf',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

