[rabbitmq]
host = '127.0.0.1'
port = 5672
user = 'www'
password = 'change-me'
virtual-host = 'testing'
customer-timeout = 600

[redis]
namespace = 'testing://'
host = '127.0.0.1'
port = 6371

[app]
api-url = 'http://127.0.0.1:8000/api'
