[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "ai_translate"
version = "2026.6.28"
requires-python = ">= 3.14"
description = "An OpenAI consumer process"
readme = "README.md"
license = "MIT"

dependencies = ["pika", "requests", "redis[hiredis]", "openai"]

[project.scripts]
mint-ai-translate-consumer = "ai_translate.__main__:main"

