- name: Install api v8 dependencies
  ansible.builtin.shell: |
    npm install
    php8.1 /usr/local/bin/composer install
    cd public
    npm install
    php8.1 /usr/local/bin/composer install

    exit 0
  args:
    executable: /bin/bash
    chdir: "{{ ansible_env.HOME }}/build/mint-{{ mint_version }}/api-v8"
