- name: Prepare the env
  hosts: localhost
  tasks:
    - name: Check if mint.tar.xz file exists
      ansible.builtin.stat:
        path: "{{ playbook_dir }}/tmp/{{ app_domain }}-{{ mint_version }}.tar.xz"
      register: mint_release_file_status

- name: Building release package
  hosts: building
  roles:
    - role: mint-build-v2.3
      when: not mint_release_file_status.stat.exists
  vars:
    app_workspace: "{{ ansible_facts['env']['HOME'] }}/build/mint"
