- name: Prepare the env
  hosts: localhost
  tasks:
    - name: Check if mint.tar.xz file exists
      ansible.builtin.stat:
        path: "{{ playbook_dir }}/tmp/{{ app_domain }}-{{ mint_version }}.tar.xz"
      register: mint_release_file_status

- name: Building release package
  hosts: localhost      
  roles:
    - role: mint-build-v2.3
      when: not mint_release_file_status.stat.exists
  vars:
    app_workspace: "{{ ansible_facts['env']['HOME'] }}/build/mint"

- name: Upload and setup release package
  hosts:
    - task
    - php_fpm
    - task
    - ai_translate
    - openai_proxy
  roles:
    - role: mint-v2.3

# - name: Setup local build folder
#   hosts: localhost
#   tasks:
#     - name: Git checkout repo
#       ansible.builtin.git:
#         repo: "https://github.com/iapt-platform/mint.git"
#         dest: "{{ playbook_dir }}/tmp/mint"
#         version: "{{ mint_version }}"

# - name: Build on local
#   hosts: localhost
#   roles:
#     - mint-dashboard-v4-build
#     - mint-openai-proxy-build
#     - clove-build

# - name: Build mint package on remote
#   hosts: building
#   roles:
#     - mint-release-build

# - name: Setup deploy folder
#   hosts: all:!localhost
#   roles:
#     - mint-v2.2

# - name: Setup nginx
#   hosts:
#     - web
#   roles:
#     - mint-nginx
