ansible_user: "deploy"
ansible_python_interpreter: /usr/bin/python3
ansible_ssh_private_key_file: "{{ inventory_dir }}/.ssh/id_ed25519"

app_deploy_target: "/srv/{{ app_domain }}/{{ mint_version }}"
app_debug: false

app_api_v8_php_base_path: "/api"
app_api_v12_php_base_path: "/api-v2026"
app_dashboard_v4_base_path: "/pcd"
app_dashboard_v6_base_path: "/pcd-v2026"

app_dashboard_token_key: "token.20260116"
app_php_memory_limit: "128M"
app_consumer_loop_limit_ai_translate: 16
app_deploy_keeps: 7

app_php_fpm81_port: 9810
app_php_fpm84_port: 9840

app_php81_image: "wikipali/mint:php-8.1-20251225"
app_php84_image: "wikipali/mint:php-8.4-20260108"
app_python_image: "wikipali/mint:php-8.4-20260108"
app_nodejs_image: "wikipali/mint:php-8.4-20260108"
app_pull_images: false
