<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lily.proto

namespace Palm\Lily\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>palm.lily.v1.TeXLiveTask</code>
 */
class TeXLiveTask extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes entry = 1;</code>
     */
    protected $entry = '';
    /**
     * Generated from protobuf field <code>map<string, bytes> attachments = 3;</code>
     */
    private $attachments;
    /**
     * Generated from protobuf field <code>.palm.lily.v1.TeXLiveTask.Output output = 9;</code>
     */
    protected $output = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $entry
     *     @type array|\Google\Protobuf\Internal\MapField $attachments
     *     @type \Palm\Lily\V1\TeXLiveTask\Output $output
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Lily::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes entry = 1;</code>
     * @return string
     */
    public function getEntry()
    {
        return $this->entry;
    }

    /**
     * Generated from protobuf field <code>bytes entry = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setEntry($var)
    {
        GPBUtil::checkString($var, False);
        $this->entry = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, bytes> attachments = 3;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getAttachments()
    {
        return $this->attachments;
    }

    /**
     * Generated from protobuf field <code>map<string, bytes> attachments = 3;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setAttachments($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->attachments = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.palm.lily.v1.TeXLiveTask.Output output = 9;</code>
     * @return \Palm\Lily\V1\TeXLiveTask\Output|null
     */
    public function getOutput()
    {
        return $this->output;
    }

    public function hasOutput()
    {
        return isset($this->output);
    }

    public function clearOutput()
    {
        unset($this->output);
    }

    /**
     * Generated from protobuf field <code>.palm.lily.v1.TeXLiveTask.Output output = 9;</code>
     * @param \Palm\Lily\V1\TeXLiveTask\Output $var
     * @return $this
     */
    public function setOutput($var)
    {
        GPBUtil::checkMessage($var, \Palm\Lily\V1\TeXLiveTask\Output::class);
        $this->output = $var;

        return $this;
    }

}

