- name: Remove useless packages from the cache
  become: true
  ansible.builtin.apt:
    autoclean: true

- name: Cleans the local repository of retrieved package files that can no longer be downloaded.
  become: true
  ansible.builtin.apt:
    clean: true

- name: Remove dependencies that are no longer required
  become: true
  ansible.builtin.apt:
    autoremove: true

- name: Force systemd to reread configs
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: Release journald disk usage
  become: true
  ansible.builtin.shell: journalctl --vacuum-time=2d
