-- Your SQL goes here

ALTER TABLE fts_texts ADD id SERIAL PRIMARY KEY;
ALTER TABLE fts_texts ADD created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE fts_texts ADD updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;