// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lily.proto

package com.github.saturn_xiv.palm.plugins.lily.v1;

public interface EpubBuildRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:palm.lily.v1.EpubBuildRequest)
    com.google.protobuf.MessageOrBuilder {
}
