// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lily.proto

package com.github.saturn_xiv.palm.plugins.lily.v1;

public final class Lily {
  private Lily() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_palm_lily_v1_File_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_palm_lily_v1_File_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_palm_lily_v1_ExcelModel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_palm_lily_v1_ExcelModel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_palm_lily_v1_ExcelModel_Sheet_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_palm_lily_v1_ExcelModel_Sheet_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_palm_lily_v1_ExcelModel_Sheet_Cell_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_palm_lily_v1_ExcelModel_Sheet_Cell_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_palm_lily_v1_TexToRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_palm_lily_v1_TexToRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_palm_lily_v1_TexToRequest_FilesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_palm_lily_v1_TexToRequest_FilesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_palm_lily_v1_EpubBuildRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_palm_lily_v1_EpubBuildRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nlily.proto\022\014palm.lily.v1\"C\n\004File\022\031\n\014co" +
      "ntent_type\030\001 \001(\tH\000\210\001\001\022\017\n\007payload\030\002 \001(\014B\017" +
      "\n\r_content_type\"\266\001\n\nExcelModel\022.\n\006sheets" +
      "\030\001 \003(\0132\036.palm.lily.v1.ExcelModel.Sheet\032x" +
      "\n\005Sheet\022\014\n\004name\030\001 \001(\t\0222\n\005cells\030\002 \003(\0132#.p" +
      "alm.lily.v1.ExcelModel.Sheet.Cell\032-\n\004Cel" +
      "l\022\013\n\003row\030\001 \001(\r\022\013\n\003col\030\002 \001(\r\022\013\n\003val\030\003 \001(\t" +
      "\"r\n\014TexToRequest\0224\n\005files\030\001 \003(\0132%.palm.l" +
      "ily.v1.TexToRequest.FilesEntry\032,\n\nFilesE" +
      "ntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\014:\0028\001\"\022\n\020" +
      "EpubBuildRequest2|\n\005Excel\0227\n\005Parse\022\022.pal" +
      "m.lily.v1.File\032\030.palm.lily.v1.ExcelModel" +
      "\"\000\022:\n\010Generate\022\030.palm.lily.v1.ExcelModel" +
      "\032\022.palm.lily.v1.File\"\0002|\n\003Tex\0229\n\005ToPdf\022\032" +
      ".palm.lily.v1.TexToRequest\032\022.palm.lily.v" +
      "1.File\"\000\022:\n\006ToWord\022\032.palm.lily.v1.TexToR" +
      "equest\032\022.palm.lily.v1.File\"\0002E\n\004Epub\022=\n\005" +
      "Build\022\036.palm.lily.v1.EpubBuildRequest\032\022." +
      "palm.lily.v1.File\"\000B.\n*com.github.saturn" +
      "_xiv.palm.plugins.lily.v1P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_palm_lily_v1_File_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_palm_lily_v1_File_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_palm_lily_v1_File_descriptor,
        new java.lang.String[] { "ContentType", "Payload", "ContentType", });
    internal_static_palm_lily_v1_ExcelModel_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_palm_lily_v1_ExcelModel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_palm_lily_v1_ExcelModel_descriptor,
        new java.lang.String[] { "Sheets", });
    internal_static_palm_lily_v1_ExcelModel_Sheet_descriptor =
      internal_static_palm_lily_v1_ExcelModel_descriptor.getNestedTypes().get(0);
    internal_static_palm_lily_v1_ExcelModel_Sheet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_palm_lily_v1_ExcelModel_Sheet_descriptor,
        new java.lang.String[] { "Name", "Cells", });
    internal_static_palm_lily_v1_ExcelModel_Sheet_Cell_descriptor =
      internal_static_palm_lily_v1_ExcelModel_Sheet_descriptor.getNestedTypes().get(0);
    internal_static_palm_lily_v1_ExcelModel_Sheet_Cell_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_palm_lily_v1_ExcelModel_Sheet_Cell_descriptor,
        new java.lang.String[] { "Row", "Col", "Val", });
    internal_static_palm_lily_v1_TexToRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_palm_lily_v1_TexToRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_palm_lily_v1_TexToRequest_descriptor,
        new java.lang.String[] { "Files", });
    internal_static_palm_lily_v1_TexToRequest_FilesEntry_descriptor =
      internal_static_palm_lily_v1_TexToRequest_descriptor.getNestedTypes().get(0);
    internal_static_palm_lily_v1_TexToRequest_FilesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_palm_lily_v1_TexToRequest_FilesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_palm_lily_v1_EpubBuildRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_palm_lily_v1_EpubBuildRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_palm_lily_v1_EpubBuildRequest_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
