# https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa

- name: Add python3 stable repository from PPA and install its signing key on Ubuntu target
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:deadsnakes/ppa

- name: Update apt cache
  become: true
  ansible.builtin.apt:
    update_cache: true
    # cache_valid_time: 3600

- name: Install python3 packages
  become: true
  ansible.builtin.apt:
    pkg:
      - python{{ app_python_version }}-dev
      - python{{ app_python_version }}-venv
      - python{{ app_python_version }}-distutils
