- name: Install dependency packages
  become: true
  ansible.builtin.apt:
    pkg:
      - redis

- name: Enable redis-server service
  become: true
  ansible.builtin.systemd:
    name: redis-server
    enabled: true
    state: "restarted"

- name: Create /var/lib/redis
  become: true
  ansible.builtin.file:
    path: "/var/lib/redis/node-{{ app_redis_port }}"
    owner: redis
    group: redis
    mode: "0750"
    state: directory

- name: Upload /etc/redis.conf
  become: true
  ansible.builtin.template:
    src: redis.conf.j2
    dest: "/etc/redis/node-{{ app_redis_port }}.conf"
    owner: redis
    group: redis
    mode: "0640"

- name: Upload systemd redis-server.service
  become: true
  ansible.builtin.template:
    src: server.service.j2
    dest: "/usr/lib/systemd/system/redis-server-{{ app_redis_port }}.service"
    mode: "0644"

- name: Force systemd to reread configs
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable redis-cluster-node service
  become: true
  ansible.builtin.systemd:
    name: "redis-server-{{ app_redis_port }}"
    enabled: true
    masked: false
    state: "restarted"
