export const csParaMap = [
  { name: "pārā.", book: 213, para: 3 },
  { name: "pāci.", book: 214, para: 3 },
  { name: "mahāva.", book: 215, para: 3 },
  { name: "cūḷava.", book: 216, para: 3 },
  { name: "pari.", book: 217, para: 3 },
  { name: "pārā.aṭṭha.", book: 138, para: 3 },
  { name: "pāci.aṭṭha.", book: 139, para: 3 },
  { name: "mahāva.aṭṭha.", book: 140, para: 3 },
  { name: "cūḷava.aṭṭha.", book: 141, para: 3 },
  { name: "pari.aṭṭha.", book: 142, para: 3 },

  { name: "dī.ni.1.", book: 93, para: 3 },
  { name: "dī.ni.2.", book: 94, para: 3 },
  { name: "dī.ni.3.", book: 95, para: 3 },

  { name: "ma.ni.1.", book: 164, para: 3 },
  { name: "ma.ni.2.", book: 165, para: 3 },
  { name: "ma.ni.3.", book: 166, para: 3 },
  { name: "ma.ni.aṭṭha.1.", book: 130, para: 3 },
  { name: "ma.ni.aṭṭha.2.", book: 131, para: 3 },
  { name: "ma.ni.aṭṭha.3.", book: 132, para: 3 },
  { name: "ma.ni.ṭī.1.", book: 192, para: 3 },
  { name: "ma.ni.ṭī.2.", book: 193, para: 3 },
  { name: "ma.ni.ṭī.3.", book: 194, para: 3 },

  { name: "saṃ.ni.1.", book: 167, para: 3 },
  { name: "saṃ.ni.2.", book: 168, para: 3 },
  { name: "saṃ.ni.3.", book: 169, para: 3 },
  { name: "saṃ.ni.4.", book: 170, para: 3 },
  { name: "saṃ.ni.5.", book: 171, para: 3 },

  { name: "a.ni.1.", book: 84, para: 3 },
  { name: "a.ni.2.", book: 85, para: 3 },
  { name: "a.ni.3.", book: 86, para: 3 },
  { name: "a.ni.4.", book: 87, para: 3 },
  { name: "a.ni.5.", book: 88, para: 3 },
  { name: "a.ni.6.", book: 89, para: 3 },
  { name: "a.ni.7.", book: 90, para: 3 },
  { name: "a.ni.8.", book: 91, para: 3 },
  { name: "a.ni.9.", book: 92, para: 3 },
  { name: "a.ni.10.", book: 82, para: 3 },
  { name: "a.ni.11.", book: 83, para: 3 },
];
