// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: morus.proto

package com.github.iapt_platform.mint.plugins.morus.v1;

public final class Morus {
  private Morus() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mint_morus_v1_MarkdownToHtmlRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mint_morus_v1_MarkdownToHtmlRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mint_morus_v1_MarkdownToHtmlResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mint_morus_v1_MarkdownToHtmlResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013morus.proto\022\rmint.morus.v1\":\n\025Markdown" +
      "ToHtmlRequest\022\017\n\007payload\030\001 \001(\t\022\020\n\010saniti" +
      "ze\030\002 \001(\010\")\n\026MarkdownToHtmlResponse\022\017\n\007pa" +
      "yload\030\001 \001(\t2c\n\010Markdown\022W\n\006ToHtml\022$.mint" +
      ".morus.v1.MarkdownToHtmlRequest\032%.mint.m" +
      "orus.v1.MarkdownToHtmlResponse\"\000B2\n.com." +
      "github.iapt_platform.mint.plugins.morus." +
      "v1P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_mint_morus_v1_MarkdownToHtmlRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mint_morus_v1_MarkdownToHtmlRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mint_morus_v1_MarkdownToHtmlRequest_descriptor,
        new java.lang.String[] { "Payload", "Sanitize", });
    internal_static_mint_morus_v1_MarkdownToHtmlResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_mint_morus_v1_MarkdownToHtmlResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mint_morus_v1_MarkdownToHtmlResponse_descriptor,
        new java.lang.String[] { "Payload", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
