- name: disable autologin for ttyAMA0
  become: true
  ansible.builtin.replace:
    path: /etc/systemd/system/serial-getty@ttyAMA0.service.d/autologin.conf
    regexp: " --autologin pi "
    replace: " "
    backup: true

- name: disable autologin for tty1
  become: true
  ansible.builtin.replace:
    path: /etc/systemd/system/getty@tty1.service.d/autologin.conf
    regexp: " --autologin pi "
    replace: " "
    backup: true

- name: disable autologin for ttyS0
  become: true
  ansible.builtin.replace:
    path: /etc/systemd/system/serial-getty@ttyS0.service.d/autologin.conf
    regexp: " --autologin pi "
    replace: " "
    backup: true

- name: disable autologin for ttySAC0
  become: true
  ansible.builtin.replace:
    path: /etc/systemd/system/serial-getty@ttySAC0.service.d/autologin.conf
    regexp: " --autologin pi "
    replace: " "
    backup: true
